name: Tarea General con Criterio de Aceptación
description: Utiliza el formato de una tarea general con Objetivo, Definition of Done y Casos de Prueba, y además se agregan los Criterios de Aceptación. Ideal para tareas con Casos de Prueba basados en eventos.
body:
  - type: markdown
    attributes:
      value: |
        Por favor completá los campos debajo para crear una nueva tarea. Es importante que **SIEMPRE** tenga el mayor detalle posible para evitar confusiones.
  - type: textarea
    id: goal
    attributes:
      label: Introducción/objetivo
      description: |
        Siguiendo la definición de [Behavior Driven Design](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) se recomienda utilizar el formato "as a", "i want" y "so that" en español siempre y cuando tenga sentido: 

        - Como *[tipo de usuario o persona/rol que se beneficia de la tarea]*
        - Quiero *[objetivo que se desea alcanzar]*
        - Para que *[beneficio/valor o razón de negocio]*

        **De lo contrario, se puede describir la tarea a realizar sin ningún formato específico.**

      placeholder: El objetivo de esta tarea es...
    validations:
      required: true
  - type: textarea
    id: definition-of-done
    attributes:
      label: Definition of Done
      description: |
        Desglose de la tarea en accionables. 
        
        Lista de ítems a hacer check a medida que se considera que se avanza. Deben ser entregables o hitos bien definidos y alcanzables. Una vez chequeados todos los ítems se puede cerrar la tarea.

        Ejemplo:
        - Generar documentación para módulo 1
        - Generar documentación para módulo 2
        - Subir documentos a la plataforma XY
        - Verificar todos los Casos de Prueba

        **Es obligatorio usar [Lista de Tareas](https://docs.github.com/es/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists#creating-task-lists)**

      value: |
        - [ ] ...
    validations:
      required: true
  - type: textarea
    id: test-cases
    attributes:
      label: Casos de Prueba
      description: |
        Lista de pruebas a chequear para validar/probar que la tarea realizada sea correcta y esté efectivamente finalizada **EN BASE AL CRITERIO DEL CLIENTE**.

        **Es obligatorio usar [Lista de Tareas](https://docs.github.com/es/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists#creating-task-lists)**
      value: |
        - [ ] ...
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Criterios de Aceptación
      description: |
        Siguiendo la definición de [Behavior Driven Design](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) se recomienda utilizar el formato "given", "when" y "then" en español: 

        - Dado [contexto o estado inicial del escenario],
        - Cuando [acción o evento que desencadena el escenario],
        - Entonces [resultado esperado].
      placeholder: | 
        Se recomienda usar el formato de:
        
        ## NOMBRE DEL CRITERIO 1

        Dado [contexto o estado inicial del escenario],
        Cuando [acción o evento que desencadena el escenario],
        Entonces [resultado esperado].

        ## NOMBRE DEL CRITERIO 2

        Dado [contexto o estado inicial del escenario],
        Cuando [acción o evento que desencadena el escenario],
        Entonces [resultado esperado].

        ...
    validations:
      required: true
